### ISSUE TITLE
Error: connection handler failed

### ISSUE THREAD

**Issue by VelvetAcidChrist** [Nevysha/Cozy-Nest#104]
In terminal on startup:

-----

2023-05-19 20:42:50,267 - server.py [line:646] - INFO: connection open
2023-05-19 20:42:51,378 - server.py [line:242] - ERROR: connection handler failed
Traceback (most recent call last):
  File "I:\SD\venv\lib\site-packages\websockets\legacy\server.py", line 240, in handler
    await self.ws_handler(self)
  File "I:\SD\venv\lib\site-packages\websockets\legacy\server.py", line 1186, in _ws_handler
    return await cast(
  File "I:\SD\extensions\Cozy-Nest\scripts\cozynest_image_browser.py", line 55, in handle_client
    res = await process(data)
  File "I:\SD\extensions\Cozy-Nest\scripts\cozynest_image_browser.py", line 85, in process
    return json.dumps(data)
  File "I:\SD\python\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "I:\SD\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "I:\SD\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "I:\SD\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
2023-05-19 20:42:51,381 - server.py [line:268] - INFO: connection closed

-----

Browser не работает, AddNet тоже не работает. В чём может быть причина?

**Comment by Nevysha** [comment]
Hey !
What is "AddNet" ?

**Comment by Nevysha** [comment]
I've added an better error handling in the image browser socket. If something crash you'll have a dialog on Cozy Nest that display info for the error. You gave to enable this in Cozy Nest settings : 
![image](https://github.com/Nevysha/Cozy-Nest/assets/122687716/af05ea27-5226-4565-b2e7-dc17afd0bcad)

Please update through extension tab, restart a1111 totally and check the error.
