### ISSUE TITLE
[Issue]: Won't load, "Error executing callback ui_tabs_callback" (on fresh install of 1.2.1 OR 1.3.1)

### ISSUE THREAD

**Issue by gordingus** [Nevysha/Cozy-Nest#141]
### What happened?

Windows 10, Firefox or Chrome, A1111 vanilla webui

Tried on multiple different commits, fresh installs (of 1.2.1 and 1.3.1) with no other extensions. Only appears after I install this extension and restart.

### Webui

Automatic1111's webui

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant browser log output

```shell
Error executing callback ui_tabs_callback for D:\Program Files\Visions of Chaos\Machine Learning Files\Text To Image\stable-diffusion-webui\extensions\Cozy-Nest\scripts\nevysha_cozy_nest.py
Traceback (most recent call last):
  File "D:\Program Files\Visions of Chaos\Machine Learning Files\Text To Image\stable-diffusion-webui\modules\script_callbacks.py", line 151, in ui_tabs_callback
    res += c.callback() or []
  File "D:\Program Files\Visions of Chaos\Machine Learning Files\Text To Image\stable-diffusion-webui\extensions\Cozy-Nest\scripts\nevysha_cozy_nest.py", line 503, in on_ui_tabs
    cnib_output_folder = cnib_output_folder + list(set(output_folder_array()) - set(cnib_output_folder))
  File "D:\Program Files\Visions of Chaos\Machine Learning Files\Text To Image\stable-diffusion-webui\extensions\Cozy-Nest\scripts\nevysha_cozy_nest.py", line 208, in output_folder_array
    outdir_txt2img_samples = shared.opts.data['outdir_txt2img_samples']
KeyError: 'outdir_txt2img_samples'
```

### Checklist

- [X] I have searched the issues to make sure this is not a duplicate
- [X] Webui is up to date
- [X] Cozy-Nest is up to date
- [X] All my extensions are up to date

**Comment by Nevysha** [comment]
Please go in the json file located in the extension folder and set : 
`fetch_output_folder_from_a1111_settings : false,`
and
`cnib_output_folder: [],`

Then restart.

Not sure what the cause is but it looks like CozyNest cannot properly automatically locate your output folder
