### ISSUE TITLE
[Issue]: Forge-ui no workie

### ISSUE THREAD

**Issue by MoistifiedCoctusTM** [Nevysha/Cozy-Nest#198]
### What happened?

Crash then fallback 

### Webui

Automatic1111's webui

### What browsers are you seeing the problem on?

Something else (please specify)

### Additional info

error then fallback to standard ui despite showing ui through the error completely no clear zest i assume. using opera gx (aka og gamer edition)

### Relevant log output from the webui

```shell
2024-05-01 03:21:58,729 - ControlNet - INFO - ControlNet UI callback registered.
[CozyNest:INFO] version: 2.4.4 on auto1111
[CozyNest:INFO] CozyNest: Image browser is disabled. To enable it, go to the CozyNest settings.
*** Error executing callback ui_tabs_callback for C:\Users\Moist\Documents\A1111 WEBUI FORGE\webui\extensions\Cozy-Nest\scripts\nevysha_cozy_nest.py
    Traceback (most recent call last):
      File "C:\Users\Moist\Documents\A1111 WEBUI FORGE\webui\modules\script_callbacks.py", line 183, in ui_tabs_callback
        res += c.callback() or []
      File "C:\Users\Moist\Documents\A1111 WEBUI FORGE\webui\extensions\Cozy-Nest\scripts\nevysha_cozy_nest.py", line 189, in on_ui_tabs
        gradio_hidden_field(server_port)
      File "C:\Users\Moist\Documents\A1111 WEBUI FORGE\webui\extensions\Cozy-Nest\scripts\nevysha_cozy_nest.py", line 117, in gradio_hidden_field
        buttons = modules.generation_parameters_copypaste.create_buttons(
    AttributeError: module 'modules' has no attribute 'generation_parameters_copypaste'
```

### Checklist

- [x] I have searched the issues to make sure this is not a duplicate
- [X] Webui is up to date
- [X] Cozy-Nest is up to date
- [X] All my extensions are up to date

**Comment by enzomtpYT** [comment]
Same problem here
I just installed automatic1111's webui and wanted to have better UI, i installed cozy nest but didn't worked
I verifed im getting the smae errors in the logs
