### ISSUE TITLE
Errors after installing and enabling

### ISSUE THREAD

**Issue by Enferlain** [Nevysha/Cozy-Nest#41]
Wanted to try the extension but seeing a lot of glitches + these errors. Any idea why?

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 335, in __call__
    stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/.shortcut-targets-by-id/1jf6gnYRfcBj0hmPvmYdo8DlixdS6VewH/sd22/stable-diffusion-webui/extensions/Cozy-Nest/nevyui_settings.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 338, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path /content/drive/.shortcut-targets-by-id/1jf6gnYRfcBj0hmPvmYdo8DlixdS6VewH/sd22/stable-diffusion-webui/extensions/Cozy-Nest/nevyui_settings.json does not exist.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 335, in __call__
    stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/.shortcut-targets-by-id/1jf6gnYRfcBj0hmPvmYdo8DlixdS6VewH/sd22/stable-diffusion-webui/extensions/Cozy-Nest/nevyui_settings.json'
```

![image](https://github.com/Nevysha/Cozy-Nest/assets/15861396/af5647c8-2048-4f2b-b2bc-bf2974ffd028)

![image](https://github.com/Nevysha/Cozy-Nest/assets/15861396/bf828e40-96ca-475f-82fd-4369e44cb344)

**Comment by Nevysha** [comment]
In what environnement are you running a1111 please ?
When does those error pop in your output ?
Also please add your list of installed extension.

**Comment by Enferlain** [comment]
It's running on google colab from google drive. The error pops out as soon as I open the webui. 

Other extensions

PBRemTools
a1111-sd-webui-haku-img
a1111-sd-webui-locon
a1111-sd-webui-lyrcoris
batchlinks-webui
gif2gif
sd-3dmodel-loader
sd-civitai-browser
sd-webui-3d-open-pose-editor
sd-webui-
sd-webui-
sd-webui-
sd-webui-
sd-webui-
sd-webui-

**Comment by Nevysha** [comment]
@Enferlain You should disable  stable-diffusion-webui-catppuccin and every extension that have a huge impact on UI.
@magejosh Do you have any other extensions installed ? Which commit of a1111 are you on ? Which browser are you using ?

**Comment by Enferlain** [comment]
@Nevysha I disabled catppuccin, but I still get this the errors.

`RuntimeError: File at path /content/drive/.shortcut-targets-by-id/1jf6gnYRfcBj0hmPvmYdo8DlixdS6VewH/sd22/stable-diffusion-webui/extensions/Cozy-Nest/nevyui_settings.json does not exist.`


Can you send me nevyui_settings.json?

**Comment by Nevysha** [comment]
that's the file where your settings regarding Cozy Nest are stored so the file does not exists until you save your settings through the ui. This error should not be blocking (but will be fixed in next update). You can try creating one manually and pasting this inside : 

```
{
  "main_menu_position": "top",
  "quicksettings_position": "split",
  "accent_generate_button": false,
  "font_size": 12,
  "waves_color": "#5e1a91",
  "bg_gradiant_color": "#65005e",
  "accent_color": "#5cafd6",
  "card_height": "8",
  "card_width": "13"
}
```

Then restart a1111.

**Comment by Enferlain** [comment]
Thanks. Errors are gone and disabling catppuccin seemed to have worked.

Is this normal tho for the others tab?

![image](https://github.com/Nevysha/Cozy-Nest/assets/15861396/2c027fd9-7ea8-4e6a-a78e-25bbdbb4f624)

Anyways thanks for the help

**Comment by Nevysha** [comment]
>Others tab when it's near the edge of the window

>Update tab doesn't have an x or minimize, only has this amount of icon to make it go away
Both those issue are because of your number of extension regarding your available screen width. You can drag some of your tab inside the "Others" small panel to gain some space.

>Settings minimize button doesn't do anything
This is not a minimize but a button to move the setting around (draggable)

>Extra networks Lora tab only scrollable on the card part
Never seen that much small Lora tag O.O I'll look into it

>Clip skip amount cut off at higher than 12 font size
Will look into this also.

Thanks for your feedback !
